"""add cascade deletes

Revision ID: 0bc57844a6ab
Revises: a442f96ee128
Create Date: 2025-05-14 10:38:20.853770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc57844a6ab'
down_revision: Union[str, None] = 'a442f96ee128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Conversation_user_id_fkey', 'Conversation', type_='foreignkey')
    op.create_foreign_key(None, 'Conversation', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Message_conversation_id_fkey', 'Message', type_='foreignkey')
    op.create_foreign_key(None, 'Message', 'Conversation', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('ThreatIndicator_message_id_fkey', 'ThreatIndicator', type_='foreignkey')
    op.create_foreign_key(None, 'ThreatIndicator', 'Message', ['message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ThreatIndicator', type_='foreignkey')
    op.create_foreign_key('ThreatIndicator_message_id_fkey', 'ThreatIndicator', 'Message', ['message_id'], ['id'])
    op.drop_constraint(None, 'Message', type_='foreignkey')
    op.create_foreign_key('Message_conversation_id_fkey', 'Message', 'Conversation', ['conversation_id'], ['id'])
    op.drop_constraint(None, 'Conversation', type_='foreignkey')
    op.create_foreign_key('Conversation_user_id_fkey', 'Conversation', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###
