"""add parent_id in message

Revision ID: 1e6f2bde227b
Revises: 3ae2c4823c44
Create Date: 2025-05-09 15:32:52.573331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6f2bde227b'
down_revision: Union[str, None] = '3ae2c4823c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Message', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'Message', 'Message', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Message', type_='foreignkey')
    op.drop_column('Message', 'parent_id')
    # ### end Alembic commands ###
