"""nullable title of a conversation

Revision ID: 31a435340ecf
Revises: ed231bf6f669
Create Date: 2025-05-07 13:14:36.556068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a435340ecf'
down_revision: Union[str, None] = 'ed231bf6f669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Conversation', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Conversation', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
