"""add rag_enabled attribute

Revision ID: 38364708f2e0
Revises: 44b98cf34b35
Create Date: 2025-05-19 23:54:13.883180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38364708f2e0'
down_revision: Union[str, None] = '44b98cf34b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Message', sa.Column('rag_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Message', 'rag_enabled')
    # ### end Alembic commands ###
