"""add message type in Message

Revision ID: 410987ea4788
Revises: 8df912ddebba
Create Date: 2025-04-20 13:19:12.768645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '410987ea4788'
down_revision: Union[str, None] = '8df912ddebba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Message', sa.Column('type', sa.Text(), nullable=False))
    op.add_column('Message', sa.Column('img_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Message', 'img_url')
    op.drop_column('Message', 'type')
    # ### end Alembic commands ###
