"""modify conversation, message, threatindicator tables

Revision ID: 4953787cbc12
Revises: 6335a92c325b
Create Date: 2025-04-26 15:06:33.168884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4953787cbc12'
down_revision: Union[str, None] = '6335a92c325b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Conversation_agent_id_fkey', 'Conversation', type_='foreignkey')
    op.drop_column('Conversation', 'agent_id')
    op.add_column('Message', sa.Column('agent_id', sa.UUID(), nullable=True))
    op.add_column('Message', sa.Column('model', sa.Text(), nullable=True))
    op.add_column('Message', sa.Column('updated_at', sa.Date(), nullable=False))
    op.create_foreign_key(None, 'Message', 'Agent', ['agent_id'], ['id'])
    op.drop_column('Message', 'is_assistant')
    op.add_column('ThreatIndicator', sa.Column('is_threat', sa.Boolean(), nullable=False))
    op.drop_column('ThreatIndicator', 'is_solved')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ThreatIndicator', sa.Column('is_solved', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('ThreatIndicator', 'is_threat')
    op.add_column('Message', sa.Column('is_assistant', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Message', type_='foreignkey')
    op.drop_column('Message', 'updated_at')
    op.drop_column('Message', 'model')
    op.drop_column('Message', 'agent_id')
    op.add_column('Conversation', sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('Conversation_agent_id_fkey', 'Conversation', 'Agent', ['agent_id'], ['id'])
    # ### end Alembic commands ###
