"""modify hashed_password col to be nullable

Revision ID: 5f90650ce34b
Revises: 89e0fcbba996
Create Date: 2025-04-21 14:44:02.140716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f90650ce34b'
down_revision: Union[str, None] = '89e0fcbba996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'hashed_password',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'hashed_password',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
