"""cancel adding parent_id in message

Revision ID: 644ad0cba0a0
Revises: 1e6f2bde227b
Create Date: 2025-05-09 15:51:05.451666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644ad0cba0a0'
down_revision: Union[str, None] = '1e6f2bde227b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Message_parent_id_fkey', 'Message', type_='foreignkey')
    op.drop_column('Message', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Message', sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('Message_parent_id_fkey', 'Message', 'Message', ['parent_id'], ['id'])
    # ### end Alembic commands ###
