"""remove agent table

Revision ID: 6c71f674132d
Revises: c06ebed6dcb2
Create Date: 2025-05-12 12:55:01.813248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c71f674132d'
down_revision: Union[str, None] = 'c06ebed6dcb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Message_agent_id_fkey', 'Message', type_='foreignkey')
    op.drop_column('Message', 'agent_id')
    op.drop_table('Agent')
    op.add_column('Message', sa.Column('agent_model', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Message', sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('Message_agent_id_fkey', 'Message', 'Agent', ['agent_id'], ['id'])
    op.drop_column('Message', 'agent_model')
    op.create_table('Agent',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Agent_pkey')
    )
    # ### end Alembic commands ###
