"""add oauth columns

Revision ID: 89e0fcbba996
Revises: 410987ea4788
Create Date: 2025-04-21 14:07:18.270935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e0fcbba996'
down_revision: Union[str, None] = '410987ea4788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('oauth_id', sa.Text(), nullable=True))
    op.add_column('User', sa.Column('oauth_provider', sa.Text(), nullable=True))
    op.create_index('user_oauth_id_index', 'User', ['oauth_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_oauth_id_index', table_name='User')
    op.drop_column('User', 'oauth_provider')
    op.drop_column('User', 'oauth_id')
    # ### end Alembic commands ###
