"""add user description to threat

Revision ID: a442f96ee128
Revises: 6c71f674132d
Create Date: 2025-05-12 17:15:40.014616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a442f96ee128'
down_revision: Union[str, None] = '6c71f674132d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ThreatIndicator', sa.Column('user_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ThreatIndicator', 'user_description')
    # ### end Alembic commands ###
