"""add role in message

Revision ID: c06ebed6dcb2
Revises: 644ad0cba0a0
Create Date: 2025-05-09 17:59:16.907104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06ebed6dcb2'
down_revision: Union[str, None] = '644ad0cba0a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Message', sa.Column('role', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Message', 'role')
    # ### end Alembic commands ###
